### ISSUE TITLE
Privileged pods keeps in the SchedulingGated status

### ISSUE THREAD

**Issue by aleskandro** [outrigger-project/multiarch-tuning-operator#41]
When a privileged pod is deployed, the webhook is capable of patching the pod regardless of the service account it uses, and the pod is admitted. However, in OCP, when the pod placement controller patches the pod later, it passes through the admission plugins again and the patch does not get admitted.

# Steps to reproduce
1. Deploy the operator and the operand
2. Create a pod as in 
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
  name: test-scc
spec:
  affinity: {}
  containers:
  - args:
    - /bin/sleep
    - inf
    image: quay.io/openshifttest/hello-sdn:1.2.0
    name: test-scc
    securityContext:
      privileged: true
      runAsGroup: 0
      runAsUser: 0
      seccompProfile:
        type: Unconfined
    volumeMounts:
    - mountPath: /var/lib/kubelet/config.json
      name: node-pullsecrets
  serviceAccount: builder
  serviceAccountName: builder
  volumes:&
  - hostPath:
      path: /var/lib/kubelet/config.json
      type: File
    name: node-pullsecrets
``` 
3. oc get pods 

# Current behavior

The pod holds in the SchedulingGated status with the operator's SchedulingGate set and is stuck from being scheduled.

# Expected Behavior 

The SchedulinGate is removed and the pod scheduled.

## Workaround

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: any-scc    
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints  

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
subjects:
  - kind: ServiceAccount
    name: multiarch-manager-operator-podplacement-controller
    namespace: openshift-multiarch-manager-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'any-scc'
```
